name: Static code analysis

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [2.5, 2.6, 2.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
          ruby-version: ${{ ruby-matrix }}

    - name: Run RuboCop
      run: bundle exec rubocop --parallel